<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE settings [
        <!ELEMENT settings (mirrors|profiles|activeProfiles)*>
        <!ATTLIST settings
                xmlns:xsi CDATA #REQUIRED
                xmlns CDATA #REQUIRED
                xsi:schemaLocation CDATA #REQUIRED>
        <!ELEMENT mirrors (mirror)*>
        <!ELEMENT mirror (id|mirrorOf|url)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT mirrorOf (#PCDATA)>
        <!ELEMENT url (#PCDATA)>
        <!ELEMENT profiles (profile)*>
        <!ELEMENT profile (id|repositories|pluginRepositories)*>
        <!ELEMENT repositories (repository)*>
        <!ELEMENT repository (id|name|url|releases|snapshots)*>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT releases (enabled|updatePolicy|checksumPolicy)*>
        <!ELEMENT enabled (#PCDATA)>
        <!ELEMENT updatePolicy (#PCDATA)>
        <!ELEMENT checksumPolicy (#PCDATA)>
        <!ELEMENT snapshots (enabled|updatePolicy|checksumPolicy)*>
        <!ELEMENT pluginRepositories (pluginRepository)*>
        <!ELEMENT pluginRepository (id|name|url|releases|snapshots)*>
        <!ELEMENT activeProfiles (activeProfile)*>
        <!ELEMENT activeProfile (#PCDATA)>
        ]>
<!--<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
   &lt;!&ndash; <mirrors>
        <mirror>
            <id>artifactory</id>
            <name>Artifactory</name>
            <url>https://repo1.uhc.com/artifactory/repo</url>
            <mirrorOf>*</mirrorOf>
        </mirror>
    </mirrors>&ndash;&gt;
    <mirrors>
        <mirror>
            <id>central</id>
            <mirrorOf>*</mirrorOf>
            <url>https://repo1.maven.org/maven2/</url>
        </mirror>
    </mirrors>

    <profiles>
        <profile>
            <id>artifactory</id>
            <repositories>
                <repository>
                    <id>central</id>
                    <name>libs-releases</name>
                    <url>https://repo1.uhc.com/artifactory/libs-releases</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
                <repository>
                    <id>snapshots</id>
                    <name>libs-snapshots</name>
                    <url>https://repo1.uhc.com/artifactory/libs-snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </snapshots>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <id>central</id>
                    <name>libs-releases</name>
                    <url>https://repo1.uhc.com/artifactory/libs-releases</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
                <pluginRepository>
                    <id>snapshots</id>
                    <name>libs-snapshots</name>
                    <url>https://repo1.uhc.com/artifactory/libs-snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                        <checksumPolicy>warn</checksumPolicy>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>artifactory</activeProfile>
    </activeProfiles>
</settings>-->
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <mirrors>
        <mirror>
            <id>central</id>
            <mirrorOf>*</mirrorOf>
            <url>https://repo1.maven.org/maven2/</url>
        </mirror>
    </mirrors>

    <!-- Removed the "artifactory" profile to prevent forced use of repo1.uhc.com -->

    <activeProfiles>
        <!-- Do not activate artifactory profile -->
    </activeProfiles>

</settings>
